# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ed6ce612e2faffad3d998e182e74a32920b4178f52ba3855781abee700df44c0d53e9c13dcbe42c2e24a38e67f190dfecb3eb7dc52f660f23a03a7fe47db36e

test:
  secret_key_base: 077225e5c309f4194e2966769980817e04285b862677be3a61fd217277ef68f3f7b3f20f4c001e98102b8cfc86bdb864b5e0b3287e96abba910c7aa339c15d01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
